jest.config.js
nodemon.json
package-lock.json
package.json
routes/basic.spec.js

Initial Jest testing setup and nodemon environment variables + package.json scripts

Jest testing

---

index.js

process.env.MONGO_DB typo

---

index.js
jest.config.js
models/basic.js
package-lock.json
package.json
routes/basic.js
routes/basic.spec.js

Implemented user insertion including:
```
name: {
type: String,
required: false,
},
email: {
type: String,
required: true,
},
```

user creation testing

---

index.js
middleware/passportConfig.js
models/user.js
package-lock.json
package.json
routes/auth.js

Added google oauth
Added router auth
Added model user
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas

Boiler plate testing

---

middleware/passportConfig.js

added port number to uri

---

middleware/passportConfig.js

changed filename

---

config/passport.js

User rename to lowercase

---

routes/auth.js

changed redirect

---

index.js

fixed bugs

---

githooks.js
index.js
middleware/passportConfig.js
routes/auth.js
routes/users.js

Hotfix bugs

---

data-seeding/1-cities/index.js
index.js
models/city.js
package-lock.json
package.json
routes/city.js

Top Ten cities endpoint for clients (frontend and iOS) to render top 10 cities

Top ten cities endpoint

---

data-seeding/1-cities/index.js
index.js

Hotfix for removing duplicate city in the seeding file.

removed duplicate city

---

routes/users.js

Hot fix of importing User model that was breaking our register endpoint. It was changed from 
`const { User } = require("../models/user");`
to 
`const User = require("../models/user");`

importing User model hot fix that was breaking register endpoint

---

index.js
routes/auth.js

should allow cookies to be passed

---

index.js

added cookieparser

---

README.md

Documentation Updates - Endpoints, Data Models and Environment Variables

Readme update 001

---

index.js
routes/auth.js

added ssl to express server

---

README.md

Update Readme from http to https endpoints.

Readme Update http to https

---

README.md

- Resolve all merge conflicts locally
- Compare your `branch` with `Release-Canvas-2-Development`
- Create PR

Release-Canvas-2-Development Branch

---

config/keys.js
middleware/passportConfig.js
package-lock.json
package.json
routes/auth.js

changed login links
google:
/auth/login/google
facebook:
/auth/login/facebook
added env vars 
GOOGLE_CLIENTID
GOOGLE_CLIENTSECRET
FACEBOOK_CLIENTID (2462239797390396)
FACEBOOK_CLIENTSECRET (79db0b693372ff14b8c9917be4d2e4a2)
removed 
/auth/login
CLIENTID
CLIENTSECRET

added facebook oAuth

---

calculation-seeding/avg_commute_time_score.js

Calculate letter score for average commute time for each city based on all the cities in the database.

Calculate letter score for average commute time for each city

---

models/city.js

City model update, avg_commute_time_score and photo fields.

City model update, avg_commute_time_score and photo fields.

---

middleware/passportConfig.js
package-lock.json
routes/auth.js

Fixed bugs that wouldn't add users

---

routes/auth.js

added /auth/validation to check if logged in

---

README.md

Readme.me update - new city schema fields and seeding instructions

Readme.me update - new city schema fields and seeding instructions

---

models/user.js

updated user model

---

README.md

fixed missing . in seeding calls

---

calculation-seeding/avg_commute_time_score.js
config/ssl.js
data-seeding/1-cities/index.js
index.js
models/city.js
routes/city.js
routes/users.js

Added data from teleport and merged with data already in database.

added data from python for seeding

---

config/ssl.js

Added cosole log for debuging error with ssl.js

Patch fix to debug ssl

---

config/ssl.js

Fixed error where const was declared then reassigned, changed to var

Fixed const to var

---

index.js
models/user.js

Hot fix - user `cities` field and useFindAndModify set to false

Hot fix - user `cities` field and useFindAndModify set to false

---

README.md
routes/users.js

Readme.md also updated
REQUIRES:
HEADERS:
```
{
headers: {
Authorization: "token"
}
}
```
JSON BODY WITH FIELDS TO UPDATE (Not all fields are required)
```
{
"name": "Changed Name",
"email": "changed@email.com",
"password": "changedPassword"
}
```
NOTE: If password field is sent, there is a function that will hash the new password before storing to database.
RETURNS
```
{
"_id": "5d7acebe82c76cf25955b4e5",
"name": "Changed Name",
"email": "changedPassword",
"cities": [
...
]
}
```

New iOS Endpoint to update: name, email and password

---

routes/profile.js

added /profile to get user object

added get user object

---

calculation-seeding/nullPhotos.js
models/city.js

Function to replace null photos with a default photo
```
{
"photo": null
}
```
will now contain:
```
{
"photo": "https://letsmovehomie-city-photoes.nyc3.digitaloceanspaces.com/no-photo-available.jpg"
}
```

Function to replace null photos with a default photo

---

calculation-seeding/calcScores.js
models/city.js
routes/city.js

Added GeoJson to the mongo db to allow to search by location (lat,lng) and added corresponding endpoint. Also some restructuring of the data model to help above feature and minor bug fixes.

Patch fix to top endpoint

---

routes/users.js

Hot fix - If property is null, will not update database with a null value.
```
{
"name": null,
"email": null,
"password": null
}
```
Will not update the database.

Hot fix - If property is null, will not update database with a null value

---

README.md

added /profile endpoints to read me

added profile to readme

---

README.md
routes/city.js

New Endpoint - /city/all - returns all cities in database with only the id and name field.
GET `https://stagebe.letsmovehomie.com/city/all`
RETURNS:
```
{
"cities": [
{
"_id": "5d8117e66b3c9148110e3104",
"name": "Albuquerque, NM"
},
{
"_id": "5d8117e66b3c9148110e3105",
"name": "South Valley, NM"
},
...
]
}
```

New Endpoint - /city/all - returns all cities in database with only the id and name field

---

routes/profile.js

added put /profile
send
{
name
password
email
}

added put / update

---

routes/users.js

Hot fix - Users should not be added to the database if errors
`password.length < 6`
`password !== password2`
`!name || !email || !password || !password2`

Hot fix - Users should not be added to the database if errors

---

config/keys.js
package-lock.json
package.json

1) Dependancies was updated
2) BE was prepared and tested for deployment to Heroku + mLab MongoDB ==> "dbURI" parameter in keys.js was changed for correct connecting to mLab MongoDB. (Previous parameter "dbURI" was commented in the same file)
New changes allow deployed BE correctly connect to the instance of mLab MongoDB
The version of this BE was previously deployed to Heroku and connected to DB - users/cities tables were created/read without problems.

Deployment

---

index.js
models/user.js
package-lock.json
routes/city.js
routes/users.js

Created a new user model 
updated register endpoint  
able to register and login in postman
- [*] Complete, tested, ready to review and merge

User model

---

index.js
models/user.js
package-lock.json
routes/city.js
routes/users.js

Reverts Lambda-School-Labs/best-places-to-live-be#77

Revert "User model"

---

routes/users.js

password 2 was deleted from logical operations

---

calculation-seeding/calcScores.js

Updated calculation to update only 100 records at a time.
- [ * ] Complete, tested, ready to review and merge
- [*  ] My code follows the style guidelines of this project
- [ * ] I have performed a self-review of my own code

Updated calculation to add 100 records at a time

---

package-lock.json

fixed package json

---

routes/users.js

Reverts Lambda-School-Labs/best-places-to-live-be#83
Password2 requirements were deleted just on the test server. This feature doesn't work on master. Need to test it on the test server first.

Revert "Deployment"

---

package-lock.json

Reverts Lambda-School-Labs/best-places-to-live-be#88
Operations to fix the test server.

Revert "fixed package json"

---

calculation-seeding/calcScores.js

Reverts Lambda-School-Labs/best-places-to-live-be#86
reverts to workable version of test-server

Revert "Updated log message"

---

calculation-seeding/calcScores.js

Reverts Lambda-School-Labs/best-places-to-live-be#85
reverts to the workable version of test-server

Revert "Updated calculation to add 100 records at a time"

---

package-lock.json
package.json

installed helmet

---

routes/profile.js

Cors and https cert

---

routes/profile.js

profile bug

---

controllers/index.js
routes/auth.js

I accidentally left the app in and didnt switch to router

---

controllers/index.js
routes/auth.js

Reverts Lambda-School-Labs/best-places-to-live-be#108

Revert "I accidentally left the app in and didnt switch to router"

---

routes/auth.js

I had an undefined term. This should fix it. Maybe. We'll see.

fixed bug maybe

---

middleware/passportConfig.js

got rid of strategy

---

index.js

trying something

---

middleware/passportConfig.js

client secret wasnt a string

---

config/keys.js
middleware/passportConfig.js

figuring out how everything is linked

---

routes/auth.js

Created and added google key on .env and Heroku config  file

created and added googlekey on .env file and content heroku config file

---

index.js
models/user.js
package-lock.json
routes/users.js

Likes feature

---

routes/users.js

Dislike middleware hotfix

---

models/user.js
routes/users.js

OS { appleId } was added to User schema in [login, register, info] endpoints of user profile

iOS { appleId } was added to User schema

---

index.js
middleware/passportConfig.js
models/user.js
package-lock.json
package.json
routes/auth.js
routes/profile.js
server.js

Update the google id in user model and added token and added some dependencies

Debugging auth 

---

routes/users.js

It was missing ! for appleID and I have added it.

updated type

---

routes/city.js

Created data visual  endpoints

Data visual
